import logo from '../assets/images/architectural.png'
import magic from '../assets/images/we-build-magic.svg'
import gridImg from '../assets/images/grid-img.png'
import photo1 from '../assets/images/photoA.png'
import photo2 from '../assets/images/photoB.png'
import photo3 from '../assets/images/photoC.png'
import carroselText2 from '../assets/images/carrosel2.svg'
import arrowRight from '../assets/images/arrow_forward_black_24dp.png'
import clientsImg from '../assets/images/clients-img.png'
import gallery from '../assets/images/gallery.png'
import carroselText3 from '../assets/images/carrosel3.svg'
import sendBlack from '../assets/images/send_black.svg'
import dribbbleLine from '../assets/images/dribbble-line.svg'
import facebook from '../assets/images/facebook.svg'
import instagram from '../assets/images/instagram.svg'
import twitter from '../assets/images/twitter.svg'
import settings from '../assets/images/settings.svg'

export default { logo, magic, gridImg, photo1, photo2, photo3,  carroselText2, arrowRight, clientsImg, gallery,carroselText3, sendBlack, dribbbleLine, facebook, instagram, twitter, settings }